<?php
/**
 * Created by PhpStorm.
 * User: Albert-幸运。
 * Date: 2018/12/18
 * Time: 11:17
 */

namespace backend\controllers;
use yii\web\Response;

class Controller extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        $this->checkLang();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 检查语言
     */
    public function checkLang(){
        if (isset(\Yii::$app->session['language'])) {
            \Yii::$app->language = \Yii::$app->session['language'];
        }
    }

    public function getIp()
    {
        if (getenv("HTTP_CLIENT_IP") && strcasecmp(getenv("HTTP_CLIENT_IP"), "unknown"))
            $ip = getenv("HTTP_CLIENT_IP");
        else if (getenv("HTTP_X_FORWARDED_FOR") && strcasecmp(getenv("HTTP_X_FORWARDED_FOR"), "unknown"))
            $ip = getenv("HTTP_X_FORWARDED_FOR");
        else if (getenv("REMOTE_ADDR") && strcasecmp(getenv("REMOTE_ADDR"), "unknown"))
            $ip = getenv("REMOTE_ADDR");
        else if (isset($_SERVER['REMOTE_ADDR']) && $_SERVER['REMOTE_ADDR'] && strcasecmp($_SERVER['REMOTE_ADDR'], "unknown"))
            $ip = $_SERVER['REMOTE_ADDR'];
        else
            $ip = "unknown";
        return ($ip);
    }

    /**
     * 返回json格式
     * @param $data
     */
    public function renderJson($data){
        if (is_array($data)) {
            if (!isset($data['code']))
                $data['code'] = 0;
            if (!isset($data['msg']))
                $data['msg'] = '';
            if (!isset($data['data']))
                $data['data'] = (object)null;
            if(isset($data['data']) && is_object($data['data'])){
                $tempData = [];
                foreach($data['data'] as $key=>$value){
                    $tempData[$key] = $value;
                }
                $data['data'] = $tempData;
            }
            $data = json_encode($data, JSON_UNESCAPED_UNICODE);
        }
        if (is_object($data)) {
            if (!isset($data->code))
                $data->code = 0;
            if (!isset($data->msg))
                $data->msg = '';
            if (!isset($data->data))
                $data->data = (object)null;
            $data = json_encode($data, JSON_UNESCAPED_UNICODE);
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        echo $data;
        exit();
    }
}